---
# tasks file for sno_deploy
- name: Configure prerequisites
  ansible.builtin.import_tasks:
    file: prerequisites.yml

- name: Configure deploy-snoa script
  ansible.builtin.copy:
    dest: /usr/local/bin/deploy-sno-a
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    content: "{{ lookup('template', 'deploy-sno-a.sh') }}"

- name: Configure deploy-snob script
  ansible.builtin.copy:
    dest: /usr/local/bin/deploy-sno-b
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    content: "{{ lookup('template', 'deploy-sno-b.sh') }}"

- name: Configure deploy-openshift-all-nodes script
  ansible.builtin.copy:
    dest: /usr/local/bin/deploy-openshift-all-nodes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    content: "{{ lookup('template', 'deploy-openshift-all-nodes.sh') }}"

- name: Configure deploy-core-services script
  ansible.builtin.copy:
    dest: /usr/local/bin/deploy-core-services
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    content: "{{ lookup('template', 'deploy-core-services.sh') }}"

- name: Configure reset-environment script
  ansible.builtin.copy:
    dest: /usr/local/bin/reset-environment
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    content: "{{ lookup('template', 'reset-environment.sh') }}"