---
- name: Ensure cluster configuration directory exists
  ansible.builtin.file:
    path: /home/ansible/clusterconfigs
    owner: ansible
    group: ansible
    mode: u=rwX,g=rwX,o=-
    state: directory
  become: false

# https://docs.openshift.com/container-platform/4.14/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html
- name: Ensure all required packages are installed
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - libvirt
    - qemu-kvm
    - mkisofs
    - python3-devel
    - jq
    - ipmitool
    - /usr/bin/nmstatectl
  become: true

- name: Ensure the Ansible user has correct permissions for libvirt
  ansible.builtin.user:
    name: ansible
    groups: libvirt

- name: Ensure firewalld allows http service
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    service: http
    state: enabled
  become: true

- name: Ensure firewalld allows 8080/tcp service
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    port: 8080/tcp
    state: enabled
  become: true

- name: Ensure libvirt storage pool is defined
  community.libvirt.virt_pool:
    name: default
    command: define
    xml: "{{ lookup('template', 'storage_pool.xml') }}"
  become: true

- name: Ensure libvirt storage pool is active
  community.libvirt.virt_pool:
    name: default
    state: active
    autostart: true
  become: true

- name: Ensure network interfaces are configured
  ansible.builtin.import_role:
    name: redhat.rhel_system_roles.network

- name: Ensure RHCOS image cache directory is available
  ansible.builtin.file:
    path: /home/ansible/rhcos_image_cache
    state: directory
    owner: ansible
    group: ansible
    mode: u=rwX,g=rwX,o=-
    setype: httpd_sys_content_t

- name: Ensure install-config.yaml exists (ipi)
  ansible.builtin.copy:
    content: "{{ lookup('template', 'install-config-ipi.yaml') }}"
    dest: /home/ansible/clusterconfigs/install-config.yaml
    owner: ansible
    group: ansible
    mode: u=rwX,g=rwX,o=-
  become: false
  when: install_method == "ipi"

- name: Ensure install-config.yaml exists (agent)
  ansible.builtin.copy:
    content: "{{ lookup('template', 'install-config-agent.yaml') }}"
    dest: /home/ansible/clusterconfigs/install-config.yaml
    owner: ansible
    group: ansible
    mode: u=rwX,g=rwX,o=-
  become: false
  when: install_method == "agent"

- name: Ensure agent-config.yaml exists (agent)
  ansible.builtin.copy:
    content: "{{ lookup('template', 'agent-config.yaml') }}"
    dest: /home/ansible/clusterconfigs/agent-config.yaml
    owner: ansible
    group: ansible
    mode: u=rwX,g=rwX,o=-
  become: false
  when: install_method == "agent"

- name: Message
  ansible.builtin.debug:
    msg: |
      Please review the contents of the install-config.yaml before proceeding.
      You will also need to manually start the RHCOS image cache server
      'podman run -d --name rhcos_image_cache \ 
      -v /home/ansible/rhcos_image_cache:/var/www/html \
      -p 8080:8080/tcp \
      registry.access.redhat.com/ubi9/httpd-24:latest'
      Then run the installation command
      'openshift-baremetal-install create cluster --dir /home/ansible/clusterconfigs/ --log-level debug'
  when: install_method == "ipi"

- name: Message
  ansible.builtin.debug:
    msg: |
      Please review the contents of the install-config.yaml and agent-config.yaml
      before proceeding.
      'openshift-install --dir /home/ansible/clusterconfigs/ agent create image'
      Use the iDRAC virtual media to mount the ISO and boot from the ISO
      Montior the installation with:
      'openshift-install --dir /home/ansible/clusterconfigs/ agent wait-for bootstrap-complete --log-level debug'
  when: install_method == "agent"
