---
# tasks file for gitlab
- name: Configure registry auth
  ansible.builtin.file:
    path: /root/.docker
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Configure pull-secret
  ansible.builtin.copy:
    remote_src: true
    src: /etc/containers/auth.json
    dest: /root/.docker/config.json
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Deploy GitLab
  ansible.builtin.import_role:
    name: redhat.rhel_system_roles.podman

- name: Wait until HTTP status is 200
  ansible.builtin.uri:
    url: "http://{{ inventory_hostname }}:8444/users/sign_in"
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  register: gitlab_curl
  until: gitlab_curl.status == 200
  retries: 60
  delay: 10

- name: Create access token
  ansible.builtin.uri:
    url: http://{{ groups['witness'][0] }}:8444/oauth/token
    method: POST
    body: grant_type=password&username=root&password={{ gitlab_root_password }}
  register: gitlab_oauth
  tags:
    - gitlab-projects

- name: List projects
  ansible.builtin.uri:
    url: "http://{{ groups['witness'][0] }}:8444/api/v4/projects"
    headers:
      Authorization: "Bearer {{ gitlab_oauth.json.access_token }}"
  register: gitlab_projects
  tags:
    - gitlab-projects

- name: Create gitops project
  ansible.builtin.uri:
    url: "http://{{ groups['witness'][0] }}:8444/api/v4/projects"
    status_code:
      - 200
      - 201
    method: POST
    headers:
      Authorization: "Bearer {{ gitlab_oauth.json.access_token }}"
    body_format: json
    body:
      name: deployables-gitops
      default_branch: main
      initialize_with_readme: true
      description: "Stores artefacts required for ArgoCD"
      visibility: public
  when: "gitlab_projects.json | length == 0"
  register: gitlab_gitops_project
  tags:
    - gitlab-projects
