---
# tasks file for gitlab
- name: Configure firewalld
  ansible.builtin.import_tasks:
    file: firewalld.yml
- name: Configure Gitlab config directory
  ansible.builtin.file:
    path: /home/ansible/gitlab/config
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Configure Gitlab logs directory
  ansible.builtin.file:
    path: /home/ansible/gitlab/logs
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Configure Gitlab data directory
  ansible.builtin.file:
    path: /home/ansible/gitlab/data
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Configure registry auth
  ansible.builtin.file:
    path: /root/.docker
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Configure pull-secret
  ansible.builtin.copy:
    remote_src: true
    src: /etc/containers/auth.json
    dest: /root/.docker/config.json
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Configure GitLab pod
  containers.podman.podman_pod:
    name: gitlab-pod
    publish:
      - 8444:8444
      - 2222:2222
    generate_systemd:
      name: true
      new: false
      path: /etc/systemd/system/
      restart_policy: always
    state: started
  become: true

- name: Configure GitLab container
  containers.podman.podman_container:
    name: gitlab-app
    env:
      GITLAB_OMNIBUS_CONFIG="external_url 'http://{{ inventory_hostname }}:8444'; gitlab_rails['gitlab_shell_ssh_port'] = 2222; puma['port'] = 8445"
    image: "{{ inventory_hostname }}:8443/gitlab/gitlab-ce:latest"
    pod: gitlab-pod
    generate_systemd:
      name: true
      new: false
      path: /etc/systemd/system/
      restart_policy: always
    state: started
    volume:
      - /home/ansible/gitlab/config:/etc/gitlab:Z
      - /home/ansible/gitlab/logs:/var/log/gitlab:Z
      - /home/ansible/gitlab/data:/var/opt/gitlab:Z
  become: true

- name: Ensure GitLab pod and container services are enabled and started
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - container-gitlab-app.service
    - pod-gitlab-pod.service

- name: Wait until HTTP status is 200
  ansible.builtin.uri:
    url: "http://{{ inventory_hostname }}:8444/users/sign_in"
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  register: gitlab_curl
  until: gitlab_curl.status == 200
  retries: 60
  delay: 10

- name: Get initial GitLab credentials
  ansible.builtin.shell:
    cmd: |
      podman exec -it gitlab-app cat /etc/gitlab/initial_root_password | grep "Password:" | tr -d ' ' | cut -d ':' -f2
  register: gitlab_credentials_result

- name: debug
  ansible.builtin.debug:
    var: gitlab_credentials_result.stdout

