---
# tasks file for gitlab
- name: Configure registry auth
  ansible.builtin.file:
    path: /root/.docker
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Configure pull-secret
  ansible.builtin.copy:
    remote_src: true
    src: /etc/containers/auth.json
    dest: /root/.docker/config.json
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=-

- name: Deploy GitLab
  ansible.builtin.import_role:
    name: redhat.rhel_system_roles.podman

- name: Wait until HTTP status is 200
  ansible.builtin.uri:
    url: "http://{{ inventory_hostname }}:8444/users/sign_in"
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  register: gitlab_curl
  until: gitlab_curl.status == 200
  retries: 60
  delay: 10

- name: List projects
  ansible.builtin.shell:
    cmd: |
      export GITLAB_CREDS='root:{{ gitlab_root_password }}'
      export GITLAB_BASE_URL="http://${GITLAB_CREDS}@$(hostname -f):8444/api/v4"
      curl --request GET ${GITLAB_BASE_URL}/projects
      curl
  register: gitlab_projects