---
kind: Secret
apiVersion: v1
metadata:
  name: gitops-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
data:
  insecure: ZmFsc2U=
  name: Z2l0b3Bz
  project: ZGVmYXVsdA==
  type: Z2l0
  url: {{ 'http://' + groups['witness'][0] + ':8444/root/deployables-gitops.git' | b64encode }}
type: Opaque