---
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: "{{ cluster_name }}-{{ unid }}"
data:
  autoImportRetry: "{{ '5' | b64encode }}"
  token: "{{ openshift_auth_results.openshift_auth.api_key | b64encode }}"
  server: "{{ _api_url | b64encode }}"
type: Opaque