apiVersion: v1alpha1
kind: AgentConfig
rendezvousIP: 192.168.1.8
hosts:
  - hostname: master0
    role: master
    interfaces:
      - name: enp0s0
        macAddress: b4:45:06:f2:a4:91
      - name: enp0s1
        macAddress: b4:45:06:f2:a4:92
    networkConfig:
      interfaces:
        - name: bond0
          type: bond
          state: up
          mac-address: b4:45:06:f2:a4:91
          ipv4:
            enabled: true
            address:
              - ip: 192.168.1.8
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            options:
              miimon: "150"
            port:
              - enp0s0
              - enp1s1
      dns-resolver:
        config:
          server:
            - 172.18.0.20
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: bond0
            table-id: 254
  - hostname: worker0
    role: worker
    interfaces:
      - name: enp0s1
        macAddress: b4:45:06:f2:a4:91
      - name: enp1s0
        macAddress: b4:45:06:f2:a4:92
    networkConfig:
      interfaces:
        - name: bond0
          type: bond
          state: up
          mac-address: b4:45:06:f2:a4:91
          ipv4:
            enabled: true
            address:
              - ip: 192.168.1.9
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            options:
              miimon: "150"
            port:
              - enp0s0
              - enp1s1
      dns-resolver:
        config:
          server:
            - 172.18.0.20
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: bond0
            table-id: 254
