---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lvm-storage
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: openshift-storage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 2-operators/lvm-storage/overlays/stable-4.14
    repoURL: >-
      http://{{ groups['witness'][0] }}:8444/root/deployables-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
