---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc-configurations
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 2-operators/misc/overlays/demo
    repoURL: >-
      http://{{ groups['witness'][0] }}:8444/root/deployables-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
