---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osus
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: openshift-update-service
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 2-operators/osus/overlays/v1
    repoURL: >-
      http://{{ groups['witness'][0] }}:8444/root/deployables-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
