---
# tasks file for sno_configure
- name: Create secrets
  ansible.builtin.import_tasks:
    file: secrets.yml

- name: Create BareMetalNode
  kubernetes.core.k8s:
    host: "{{ api_url }}"
    api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    validate_certs: false
    template: worker-node-bare-metal-host.yml
