---
# tasks file for sno_configure
- name: Enable provisioning using virtual media
  kubernetes.core.k8s:
    host: "{{ api_url }}"
    api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    validate_certs: false
    resource_definition:
      apiVersion: metal3.io/v1alpha1
      kind: Provisioning
      metadata:
        name: provisioning-configuration
      spec:
        provisioningNetwork: Disabled
        virtualMediaViaExternalNetwork: true

- name: Create secrets
  ansible.builtin.import_tasks:
    file: secrets.yml

- name: Create MachineSet
  kubernetes.core.k8s:
    host: "{{ api_url }}"
    api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    validate_certs: false
    resource_definition:
      apiVersion: machine.openshift.io/v1beta1
      kind: MachineSet
      metadata:
        name: worker
        namespace: openshift-machine-api
      spec:
        replicas: 1
        selector:
          matchLabels:
            machine.openshift.io/cluster-api-cluster: k8s
            machine.openshift.io/cluster-api-machineset: worker
        template:
          metadata:
            labels:
              machine.openshift.io/cluster-api-cluster: k8s
              machine.openshift.io/cluster-api-machine-role: worker
              machine.openshift.io/cluster-api-machine-type: worker
              machine.openshift.io/cluster-api-machineset: worker
          spec:
            metadata: {}
            providerSpec:
              value:
                apiVersion: baremetal.cluster.k8s.io/v1alpha1
                hostSelector: {}

- name: Create BareMetalNode
  kubernetes.core.k8s:
    host: "{{ api_url }}"
    api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    validate_certs: false
    template: worker-node-bare-metal-host.yml