---
- name: Configure bmc secret
  kubernetes.core.k8s:
    host: "{{ api_url }}"
    api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    validate_certs: false
    resource_definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: worker-bmc-creds
        namespace: openshift-machine-api
      data:
        username: root
        password: "{{ worker_idrac_password | b64encode }}"
      type: Opaque

- name: Configure network secret
  kubernetes.core.k8s:
    host: "{{ api_url }}"
    api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    validate_certs: false
    resource_definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: worker-network-config
        namespace: openshift-machine-api
      stringData:
        nmstate: |
          interfaces:
            - name: bond0
              type: bond
              state: up
              mac-address: b4:45:06:f1:0d:d1
              ipv4:
                enabled: true
                dhcp: true
                auto-dns: true
                auto-gateway: true
                auto-routes: true
              ipv6:
                enabled: false
              link-aggregation:
                mode: 802.3ad
                options:
                  miimon: "140"
                port:
                  - eno1
                  - eno2
      type: Opaque