---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: update-service-subscription
  namespace: openshift-update-service
spec:
  channel: v1
  installPlanApproval: Automatic
  source: redhat-operators-mirrored
  sourceNamespace: openshift-marketplace
  name: cincinnati-operator
