---
# tasks file for network
- name: Ensure configs directory exists
  ansible.builtin.file:
    path: "{{ inventory_path }}/configs"
    ensure: directory
    mode: u=rwX,g=rwX,o=-
    owner: ansible
    group: ansible
  become: false

- name: Ensure backups directory exists
  ansible.builtin.file:
    path: "{{ inventory_path }}/configs/backups"
    ensure: directory
    mode: u=rwX,g=rwX,o=-
    owner: ansible
    group: ansible
  become: false

- name: Ensure candidate directory exists
  ansible.builtin.file:
    path: "{{ inventory_path }}/configs/candidate"
    ensure: directory
    mode: u=rwX,g=rwX,o=-
    owner: ansible
    group: ansible
  become: false

- name: Retrieve current configuration to allow rollback
  juniper.device.config:
    retrieve: committed
    dest_dir: "{{ inventory_path }}/configs/backups"
    format: set

- name: Create config files
  ansible.builtin.template:
    src: qfx.j2
    dest: "{{ inventory_path }}/configs/candidate/{{ inventory_hostname }}.set"

- name: Configure host
  juniper.device.config:
    load: set
    src: "{{ inventory_path }}/configs/candidate/{{ inventory_hostname }}.set"
