---
- name: Configure firewalld for Quay ports
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    port: "{{ item }}"
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp
    - 5432/tcp
    - 5433/tcp
    - 6379/tcp
