---
- name: Configure mirror registry directory
  ansible.builtin.file:
    path: /home/ansible/mirror_registry
    mode: u=rwX,g=rwX,o=-
    owner: root
    group: root
    state: directory
  become: true

- name: Copy over image archive for initial import
  ansible.builtin.copy:
    src: archive/mirror_seq1_000000.tar
    dest: /home/ansible/
    mode: u=rwX,g=rwX,o=rX
    owner: root
    group: root
  become: true

- name: Deploy the mirror registry
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/mirror-registry install \
      --quayHostname {{ inventory_hostname }} \
      --quayRoot /home/ansible/mirror_registry \
      --initUser init \
      --initPassword "{{ mirror_registry_init_password }}"
      --sslCheckSkip \
      --no-color
    creates: /home/ansible/mirror_registry/quay-rootCA
  become: true

- name: Push oc-mirror content to the mirror registry
  ansible.builtin.shell:
    cmd: >-
      /usr/bin/podman login https://{{ inventory_hostname }}:8443 
      --tls-verify=false 
      --username init 
      --password "{{ mirror_registry_init_password }}" && 
      /usr/local/bin/oc-mirror 
      --dest-skip-tls 
      --from=/home/ansible/mirror_seq1_000000.tar 
      docker://{{ inventory_hostname }}:8443
  become: true
  tags:
   - mirror-push
