apiVersion: samples.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  architectures:
    - x86_64
  managementState: Removed
