---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lvms-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: <patch-me>
  installPlanApproval: Automatic
  name: lvms-operator
  source: redhat-operators-mirrored
  sourceNamespace: openshift-marketplace
