apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
    - name: httpd-app
      image: "{{ inventory_hostname }}:8443/ubi9/httpd-24:latest"
      ports:
        - containerPort: 8888
          hostPort: 8888
      volumeMounts:
        - mountPath: /var/www/html:Z
          name: httpd-data
  volumes:
    - name: httpd-data
      hostPath:
        path: /home/ansible/ocp-isos